### ISSUE TITLE
Docker build instruction out dated

### ISSUE THREAD

**Issue by Heziode** [godunko/adawebpack#19]
The following link for the docker build does not work: https://download.copr.fedorainfracloud.org/results/reznik/adawebpack/fedora-36-x86_64/05068491-adawebpack/adawebpack-22.1.0-git.fc36.x86_64.rpm

Is there a new version available?

@reznikmm

**Comment by reznikmm** [comment]
Thank you for the issue.

Should be fixed by #20

Don't hesitate to ask any questions.
