### ISSUE TITLE
Question about nested subprograms

### ISSUE THREAD

**Issue by ec-c** [godunko/adawebpack#21]
Why are nested subprograms not supported? Is this a technical decision or for another reason?

**Comment by godunko** [comment]
Support of nested subprograms requires features that was not supported by GNAT/LLVM/WASM at the time of the development.

**Comment by ec-c** [comment]
Does this mean that GNAT/LLVM/WASM now supports the required features to implement nested subprograms?

UPDATE: I think so because my subroutines seem to compile.

**Comment by godunko** [comment]
Actually, it did for some extent. It is safe to state that they are not supported, than try to research all conditions when GNAT's code generator reach WASM's limitations.
