### ISSUE TITLE
Support for iterator interfaces

### ISSUE THREAD

**Issue by ec-c** [godunko/adawebpack#22]
Hi there

I have implemented my own custom iterators for my data structures. But I can't compile them with adawebpack, because I currently get a `not a predefined library unit` error when I try to include the `Ada.Iterator_Interfaces` package.

Could you please add support for this interface (a-iteint.ads)?

Thank you.

**Comment by godunko** [comment]
Thank you for request, support of `Ada.Iterator_Interfaces` has been added.

Right now, you can copy `a-iteint.ads` into you code base and use `-gnatg` switch to compile it.
